name: 'Rc Slack Notify'
description: 'RateCity slack notificaion to new pull requests'
author: 'Bo Yuan'

inputs:
  SLACK_WEBHOOK:
    description: 'Slack webhook'
    required: true
  SLACK_USERNAME:
    description: 'Slack username'
    required: true
    default: 'rcbot'
  SLACK_CHANNEL:
    description: 'Slack channel'
    required: true
  SLACK_COLOR:
    description: 'Slack color'
    required: true
  SLACK_SUCCESS_MESSAGE:
    description: 'Slack success message'
    required: false
  SLACK_FAILURE_MESSAGE:
    description: 'Slack failure message'
    required: false
  SLACK_ICON:
    description: 'Slack icon'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
